repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: mixed-line-ending
  # Python
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff-format
  # BibTeX
  - repo: local
    hooks:
      - id: check-bibtex
        name: check-bibtex
        entry: python .scripts/check-bibtex.py
        language: python
        types: [bib]
        additional_dependencies: ["bibtexparser==2.0.0b7"]
  - repo: https://github.com/njzjz/mirrors-bibtex-tidy
    rev: v1.13.0
    hooks:
      - id: bibtex-tidy
        args:
          - --curly
          - --numeric
          - --align=13
          - --blank-lines
          - --sort=key
          - --duplicates=key,doi,citation,abstract
          - --merge=combine
          - --sort-fields
          - --strip-comments
          - --trailing-commas
          - --encode-urls
          - --remove-empty-fields
          - --wrap=80
