name: New BibTeX item
description: Generate a new BibTeX item from a DOI identifier.
title: "/new "
labels: ["new"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Please provide the DOI identifier in the title of this issue. For example: `/new 10.1063/5.0155600`.
  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Confirm the title is correct.
      options:
        - label: I confirm the title is correct.
          required: false
